name: Documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate documentation
        run: |
          npm install
          npm run docs:build
          git checkout --orphan www
          mv docs old-docs
          mv old-docs/_site docs
          rm -rf old-docs
          git add .
          git config --global user.name 'Eduardo Grajeda'
          git config --global user.email 'egrajeda@users.noreply.github.com'
          git commit -m "Add generated documentation"
          git push -f origin www